blueprint:
  name: Motion-activated Switch
  description: Turn on a switch when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion   
    switch_target:
      name: Switch
      selector:
        target:
          entity:
            domain: switch
    time_from:
      name: Active from
      description: A time input which defines the time from which motion is detected
      selector:
        time: {}
    time_to:
      name: Active to
      description: A time input which defines the time to which motion is detected
      selector:
        time: {}        
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input 'motion_entity'
  from: "off"
  to: "on"
condition:
- condition:
  after: !input 'time_from'
  before: !input 'time_to'
action:
- service: switch.turn_on
  target: !input 'switch_target'
- wait_for_trigger:
    platform: state
    entity_id: !input 'motion_entity'
    from: "on"
    to: "off"
- delay: !input 'no_motion_wait'
- service: switch.turn_off
  target: !input 'switch_target'